Vortex.Proj.Web/Vortex.Manager.WebApp/Controllers/AuthSystemController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Vortex.Manager.Application.DTOs.Input.Usuario;
using Microsoft.AspNetCore.Authorization;
using Vortex.Manager.Application.Interfaces.Services; 
using Vortex.Manager.Domain.Entity;

namespace Vortex.Manager.WebApp.Controllers
{
    public class AuthSystemController : Controller
    {
        private IUsuarioService _usuarioSerivce;

        public AuthSystemController(IUsuarioService usuarioSerivce)
        {
            _usuarioSerivce = usuarioSerivce;
        }

        public async Task<ActionResult> IndexAsync()
        {
            await SignOutAsync();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> LoginAsync(LoginDTO dto)
        {
            try
            {
                await SignOutAsync();

                Usuario? usuario = new Usuario { Email = dto.Email, Senha = dto.Password };
                usuario = await _usuarioSerivce.GetAsync(usuario);

                if (usuario != null)
                {
                    var claims = new List<Claim>();
                    claims.Add(new Claim(ClaimTypes.Email, usuario.Email));
                    claims.Add(new Claim(ClaimTypes.Name, usuario?.Nome ?? ""));
                    claims.Add(new Claim(ClaimTypes.Role, "Admin"));
                    claims.Add(new Claim("IdUser", $"{usuario.Id}"));

                    var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

                    await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity));

                    return RedirectToAction("Index", "Home");
                } 
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return RedirectToAction("Index", "Home");
           
        }

        public async Task<IActionResult> Logout()
        {
            await SignOutAsync();
            return RedirectToAction("Index");
        }

        private async Task SignOutAsync()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
        }

       [Authorize]
        public ActionResult Create()
        {
            if (User.FindFirstValue(ClaimTypes.Email).Equals("master@gmail.com"))
                return View();
            else
                return RedirectToAction("Index", "Home");
        }

        [Authorize] 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CreateUsuarioDTO dto)
        {
            try
            {
                if (User.FindFirstValue(ClaimTypes.Email).Equals("master@gmail.com"))
                { 
                    await _usuarioSerivce.AddAsync(new Usuario { Email = dto.Email, Senha = dto.Email, Nome = dto.Nome });
                }

                return RedirectToAction("Index", "Home");
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", "Home");
            }
        }
    }
}

Vortex.Proj.Web/Vortex.Manager.WebApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Security.Claims;
using Vortex.Manager.WebApp.Models;

namespace Vortex.Manager.WebApp.Controllers
{
    [Authorize(Roles = "Admin")]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            ViewBag.Admin = false;
          
            if (User.FindFirstValue(ClaimTypes.Email).Equals("master@gmail.com"))
                ViewBag.Admin = true;

            return View();
        }

        public IActionResult Noticias()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Vortex.Proj.Web/Vortex.Manager.WebApp/Controllers/NoticiasController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Vortex.Manager.Application.DTOs.Input.Noticia;
using Vortex.Manager.Application.Interfaces;
using Vortex.Manager.Application.Interfaces.Services;
using Vortex.Manager.Application.Mappers;
using Vortex.Manager.Domain.Entity;

namespace Vortex.Manager.WebApp.Controllers
{
    [Authorize]
    [Route("[controller]")]
    public class NoticiasController : Controller
    {
        private IHandler<RequestNoticiaDTO, Noticia> _handlerNoticias;
        private INoticiaService _noticiaService;
        private INoticiaTagService _noticiaTagService;

        public NoticiasController(IHandler<RequestNoticiaDTO, Noticia> handlerNoticias, INoticiaService noticiaService, INoticiaTagService noticiaTagService)
        {
            _handlerNoticias = handlerNoticias;
            _noticiaService = noticiaService;
            _noticiaTagService = noticiaTagService;
        }

        [HttpGet("Get")]
        public async Task<IActionResult> Get() => Ok(await _noticiaService.GetAsync().Result.Map());

        [HttpGet("GetNoticia/{id}")]
        public async Task<IActionResult> GetNoticia(int id) => Ok(await _noticiaService.GetAsync(id).Result.Map());

        [HttpPost("Create")]
        public async Task<IActionResult> Create(RequestNoticiaDTO dto)
        {
            try
            {
                //Criar Noticia
                var noticia = await _handlerNoticias.ExecutarAsync(dto);
                noticia = await _noticiaService.AddAsync(noticia);

                //Relacionar com as Tags
                var tagsNoticias = await noticia.Map(dto.TagsId);
                await _noticiaTagService.AddAsync(tagsNoticias);

                return CreatedAtAction(null, await _noticiaService.GetAsync(noticia.Id).Result.Map());
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

        [HttpPut("Edit")]
        public async Task<IActionResult> Edit(RequestNoticiaDTO dto)
        {
            try
            {
                //Edit Noticia
                var noticia = await _handlerNoticias.ExecutarAsync(dto);
                noticia = await _noticiaService.UpdateAsync(noticia);

                //Relacionar com as Tags
                var tagsNoticias = await noticia.Map(dto.TagsId);
                await _noticiaTagService.RemoveNoticiaAll(noticia.Id);
                await _noticiaTagService.AddAsync(tagsNoticias);

                return Ok(await _noticiaService.GetAsync(dto.Id).Result.Map());
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

        [HttpDelete("Delete/{id}")]
        public async Task<IActionResult> Delete(int id)
        {
            try
            { 
                await _noticiaTagService.RemoveNoticiaAll(id);
                await _noticiaService.RemoveAsync(id);
                return Ok(new { Id = id, Mensagem = "A Noticia Foi Excluida Com Sucesso!" });
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message );
            }
        }
    }
}

Vortex.Proj.Web/Vortex.Manager.WebApp/Controllers/TagsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Vortex.Manager.Application.DTOs.Input.Tag;
using Vortex.Manager.Application.Interfaces;
using Vortex.Manager.Application.Interfaces.Services;
using Vortex.Manager.Application.Mappers; 
using Vortex.Manager.Domain.Entity;

namespace Vortex.Manager.WebApp.Controllers
{
    [Authorize] 
    public class TagsController : Controller
    {
        private IHandler<RequestTagDTO, Tag> _handlerTag;
        private ITagsService _service;
        private INoticiaTagService _noticiaTagService;

        public TagsController(IHandler<RequestTagDTO, Tag> handlerTag, ITagsService service, INoticiaTagService noticiaTagService)
        {
            _handlerTag = handlerTag;
            _service = service;
            _noticiaTagService = noticiaTagService;
        }

        public async Task<IActionResult> Index()
        {
            if (User.FindFirstValue(ClaimTypes.Email).Equals("master@gmail.com")) 
                return View(await _service.GetALLAsync().Result.Map());


            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public async Task<IActionResult> Get()
        {
            return Ok(await _service.GetALLAsync().Result.Map());
        }

        [HttpPost]
        public async Task<IActionResult> Create(RequestTagDTO dto)
        {
            try
            {
                var tag = await _handlerTag.ExecutarAsync(dto);
                tag = await _service.AddAsync(tag);
                var result = await tag.Map();
                return Ok(result);
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

        [HttpPut]
        public async Task<IActionResult> Put(RequestTagDTO dto)
        {
            try
            {
                var tag = await _handlerTag.ExecutarAsync(dto);
                tag = await _service.UpdateAsync(tag);
                var result = await tag.Map();
                return Ok(result);
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                await _noticiaTagService.RemoveTagAll(id);
                await _service.RemoveAsync(id);
                return Ok(new { Id = id, Mensagem = "A tag foi removida com sucesso!" });
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }
    }
}

Vortex.Proj.Web/Vortex.Manager.WebApp/Views/Home/Index.cshtml
<div class="body-container">
    <!-- Cabeçalho -->
    <header class="container mt-4">
        <div class="row">
            <div class="col-12">
                <h1 class="text-center">Bem-vindo ao Manager Notícias</h1>
                <p class="lead text-center">Gerencie suas notícias com eficiência e controle total.</p>
            </div>
        </div>
    </header>

    <!-- Card de Ações -->
    <section class="container mt-5">
        <div class="row">
            <div class="col-md-4">
                <div class="card text-white bg-primary mb-4">
                    <div class="card-header">Adicionar Usúario</div>
                    <div class="card-body">
                        <p>Insira novos usúarios ao sistema.</p>

                        @if (ViewBag.Admin == true)
                        {
                            <a asp-action="create" asp-controller="AuthSystem" class="btn btn-light">Adicionar Usúarios</a>
                        }
                        else
                        {
                            <a onclick="notification.addNotification('Você não é Admin!', 'error')" class="btn btn-light">Adicionar Usúarios</a>
                        }

                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card text-white bg-success mb-4">
                    <div class="card-header">Visualizar Notícia</div>
                    <div class="card-body">
                        <p>Consulte todas as notícia cadastradas.</p>
                        <a class="btn btn-light" asp-area="" asp-controller="Home" asp-action="Noticias">Ver Notícias</a>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card text-white bg-warning mb-4">
                    <div class="card-header">Gerenciar Tags </div>
                    <div class="card-body">
                        <p>Gerencie as tags do sistema. </p>
                        <a class="btn btn-light" asp-controller="Tags" asp-action="Index">Gerenciar Tags</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

Vortex.Proj.Web/Vortex.Manager.WebApp/Views/Home/Noticias.cshtml
<link rel="stylesheet" href="~/css/noticia.tag.css" asp-append-version="true" />

<div class="row">
    <div class="col-10"></div>
    <div class="col-2">
        @* <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#tagModal"> *@
        <button type="button" class="btn btn-primary" onclick="app.addNoticia()">
            Adicionar Notícia
        </button>  
    </div>
</div>
 
<h3>Notícias</h3>
<hr />

<div id="body-noticias"> </div>

@Html.Partial("_Modal");
<script src="~/js/noticia.tag.js" asp-append-version="true"></script>

Vortex.Proj.Web/Vortex.Manager.WebApp/Views/Home/_Modal.cshtml
<div class="modal fade" id="tagModal" tabindex="-1" aria-labelledby="tagModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="tagModalLabel">Gerenciar Notícias</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-9"></div>
                    <div class="col-3">
                        <button type="button" class="btn btn-danger" id="addTagDisplay">Add Tag</button>
                    </div>
                </div>
                <div id="tagFormBody">
                    <div class="mb-3">
                        <label for="elementoTitulo" class="form-label">Título:</label>
                        <input type="text" class="form-control" id="modalTitulo" required>
                    </div>
                    <div class="mb-3">
                        <label for="elementoDescricao" class="form-label">Descrição:</label>
                        <textarea class="form-control" id="modalDescricao" rows="3"></textarea> @* Campo de texto multilinha *@
                    </div> 
                </div>

                <form id="tagForm" style="display:none">
                    <div class="mb-3">
                        <label for="tagName" class="form-label">Nome da Tag:</label>
                        <input type="text" class="form-control" id="tagName" required>
                    </div>
                    <button type="button" class="btn btn-success" id="addTag">Adicionar Tag</button>
                </form>

                <hr>
                <h3>Tags:</h3>
                <div id="tagList">
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="saveNoticia">Salvar Alterações</button>
            </div>
        </div>
    </div>
</div>