Vortex.Proj.Web/Vortex.Manager.WebApp/Controllers/AuthSystemController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Vortex.Manager.Application.DTOs.Input.Usuario;
using Microsoft.AspNetCore.Authorization;
using Vortex.Manager.Application.Interfaces.Services; 
using Vortex.Manager.Domain.Entity;

namespace Vortex.Manager.WebApp.Controllers
{
    public class AuthSystemController : Controller
    {
        private IUsuarioService _usuarioSerivce;

        public AuthSystemController(IUsuarioService usuarioSerivce)
        {
            _usuarioSerivce = usuarioSerivce;
        }

        public async Task<ActionResult> IndexAsync()
        {
            await SignOutAsync();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> LoginAsync(LoginDTO dto)
        {
            try
            {
                await SignOutAsync();

                Usuario? usuario = new Usuario { Email = dto.Email, Senha = dto.Password };
                usuario = await _usuarioSerivce.GetAsync(usuario);

                if (usuario != null)
                {
                    var claims = new List<Claim>();
                    claims.Add(new Claim(ClaimTypes.Email, usuario.Email));
                    claims.Add(new Claim(ClaimTypes.Name, usuario?.Nome ?? ""));
                    claims.Add(new Claim(ClaimTypes.Role, "Admin"));
                    claims.Add(new Claim("IdUser", $"{usuario.Id}"));

                    var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

                    await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity));

                    return RedirectToAction("Index", "Home");
                } 
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return RedirectToAction("Index", "Home");
           
        }

        public async Task<IActionResult> Logout()
        {
            await SignOutAsync();
            return RedirectToAction("Index");
        }

        private async Task SignOutAsync()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
        }

       [Authorize]
        public ActionResult Create()
        {
            if (User.FindFirstValue(ClaimTypes.Email).Equals("master@gmail.com"))
                return View();
            else
                return RedirectToAction("Index", "Home");
        }

        [Authorize] 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CreateUsuarioDTO dto)
        {
            try
            {
                if (User.FindFirstValue(ClaimTypes.Email).Equals("master@gmail.com"))
                { 
                    await _usuarioSerivce.AddAsync(new Usuario { Email = dto.Email, Senha = dto.Email, Nome = dto.Nome });
                }

                return RedirectToAction("Index", "Home");
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", "Home");
            }
        }
    }
}

Vortex.Proj.Web/Vortex.Manager.WebApp/Controllers/NoticiasController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Vortex.Manager.Application.DTOs.Input.Noticia;
using Vortex.Manager.Application.Interfaces;
using Vortex.Manager.Application.Interfaces.Services;
using Vortex.Manager.Application.Mappers;
using Vortex.Manager.Domain.Entity;

namespace Vortex.Manager.WebApp.Controllers
{
    [Authorize]
    [Route("[controller]")]
    public class NoticiasController : Controller
    {
        private IHandler<RequestNoticiaDTO, Noticia> _handlerNoticias;
        private INoticiaService _noticiaService;
        private INoticiaTagService _noticiaTagService;

        public NoticiasController(IHandler<RequestNoticiaDTO, Noticia> handlerNoticias, INoticiaService noticiaService, INoticiaTagService noticiaTagService)
        {
            _handlerNoticias = handlerNoticias;
            _noticiaService = noticiaService;
            _noticiaTagService = noticiaTagService;
        }

        [HttpGet("Get")]
        public async Task<IActionResult> Get() => Ok(await _noticiaService.GetAsync().Result.Map());

        [HttpGet("GetNoticia/{id}")]
        public async Task<IActionResult> GetNoticia(int id) => Ok(await _noticiaService.GetAsync(id).Result.Map());

        [HttpPost("Create")]
        public async Task<IActionResult> Create(RequestNoticiaDTO dto)
        {
            try
            {
                //Criar Noticia
                var noticia = await _handlerNoticias.ExecutarAsync(dto);
                noticia = await _noticiaService.AddAsync(noticia);

                //Relacionar com as Tags
                var tagsNoticias = await noticia.Map(dto.TagsId);
                await _noticiaTagService.AddAsync(tagsNoticias);

                return CreatedAtAction(null, await _noticiaService.GetAsync(noticia.Id).Result.Map());
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

        [HttpPut("Edit")]
        public async Task<IActionResult> Edit(RequestNoticiaDTO dto)
        {
            try
            {
                //Edit Noticia
                var noticia = await _handlerNoticias.ExecutarAsync(dto);
                noticia = await _noticiaService.UpdateAsync(noticia);

                //Relacionar com as Tags
                var tagsNoticias = await noticia.Map(dto.TagsId);
                await _noticiaTagService.RemoveNoticiaAll(noticia.Id);
                await _noticiaTagService.AddAsync(tagsNoticias);

                return Ok(await _noticiaService.GetAsync(dto.Id).Result.Map());
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

        [HttpDelete("Delete/{id}")]
        public async Task<IActionResult> Delete(int id)
        {
            try
            { 
                await _noticiaTagService.RemoveNoticiaAll(id);
                await _noticiaService.RemoveAsync(id);
                return Ok(new { Id = id, Mensagem = "A Noticia Foi Excluida Com Sucesso!" });
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message );
            }
        }
    }
}

Vortex.Proj.Web/Vortex.Manager.WebApp/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Authorization;
@inject IAuthorizationService AuthorizationService

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Vortex.Manager.WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

    @if (User.Identity.IsAuthenticated)
    {
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    }
    else
    {
        <link rel="stylesheet" href="~/css/authsystem.css" asp-append-version="true" />
    }

    <link rel="stylesheet" href="~/Vortex.Manager.WebApp.styles.css" asp-append-version="true" />

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>
    @if (User.Identity.IsAuthenticated)
    {
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container">
                    <a class="navbar-brand c-hover" asp-area="" asp-controller="Home" asp-action="Index">Vortex.Manager</a>

                    <button class="navbar-toggler c-hover" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            @*                             <li class="nav-item">
                        <a class="nav-link text-dark c-hover" asp-area="" asp-controller="Noticias" asp-action="Index">Notícias</a>
                        </li> *@
                            <li class="nav-item">
                                <a class="nav-link text-dark c-hover" asp-area="" asp-controller="AuthSystem" asp-action="Logout">Sair</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
    }

    <div class="container">
        <div id="notificacao-erro"> 
        </div>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @if (User.Identity.IsAuthenticated)
    {
        <!-- Rodapé -->
        <footer id="footer-home" class="bg-dark text-white text-center py-3 mt-5">
            <p>&copy; 2025 Sistema de Gerenciamento de Notícias</p>
        </footer>
    }

    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>